/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsTitleRouteRouteImport } from './routes/projects/$title/route'
import { Route as ProjectsTitleIndexRouteImport } from './routes/projects/$title/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTitleRouteRoute = ProjectsTitleRouteRouteImport.update({
  id: '/projects/$title',
  path: '/projects/$title',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTitleIndexRoute = ProjectsTitleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsTitleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkRoute
  '/projects/$title': typeof ProjectsTitleRouteRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$title/': typeof ProjectsTitleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$title': typeof ProjectsTitleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkRoute
  '/projects/$title': typeof ProjectsTitleRouteRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$title/': typeof ProjectsTitleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/work'
    | '/projects/$title'
    | '/projects/'
    | '/projects/$title/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/work'
    | '/projects'
    | '/projects/$title'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/profile'
    | '/work'
    | '/projects/$title'
    | '/projects/'
    | '/projects/$title/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  WorkRoute: typeof WorkRoute
  ProjectsTitleRouteRoute: typeof ProjectsTitleRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$title': {
      id: '/projects/$title'
      path: '/projects/$title'
      fullPath: '/projects/$title'
      preLoaderRoute: typeof ProjectsTitleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$title/': {
      id: '/projects/$title/'
      path: '/'
      fullPath: '/projects/$title/'
      preLoaderRoute: typeof ProjectsTitleIndexRouteImport
      parentRoute: typeof ProjectsTitleRouteRoute
    }
  }
}

interface ProjectsTitleRouteRouteChildren {
  ProjectsTitleIndexRoute: typeof ProjectsTitleIndexRoute
}

const ProjectsTitleRouteRouteChildren: ProjectsTitleRouteRouteChildren = {
  ProjectsTitleIndexRoute: ProjectsTitleIndexRoute,
}

const ProjectsTitleRouteRouteWithChildren =
  ProjectsTitleRouteRoute._addFileChildren(ProjectsTitleRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  WorkRoute: WorkRoute,
  ProjectsTitleRouteRoute: ProjectsTitleRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
