/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkTitleRouteRouteImport } from './routes/work/$title/route'
import { Route as WorkTitleIndexRouteImport } from './routes/work/$title/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTitleRouteRoute = WorkTitleRouteRouteImport.update({
  id: '/work/$title',
  path: '/work/$title',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTitleIndexRoute = WorkTitleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkTitleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/work/$title': typeof WorkTitleRouteRouteWithChildren
  '/work/': typeof WorkIndexRoute
  '/work/$title/': typeof WorkTitleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkIndexRoute
  '/work/$title': typeof WorkTitleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/work/$title': typeof WorkTitleRouteRouteWithChildren
  '/work/': typeof WorkIndexRoute
  '/work/$title/': typeof WorkTitleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/development'
    | '/privacy'
    | '/profile'
    | '/work/$title'
    | '/work/'
    | '/work/$title/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/development'
    | '/privacy'
    | '/profile'
    | '/work'
    | '/work/$title'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/development'
    | '/privacy'
    | '/profile'
    | '/work/$title'
    | '/work/'
    | '/work/$title/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DevelopmentRoute: typeof DevelopmentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  WorkTitleRouteRoute: typeof WorkTitleRouteRouteWithChildren
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$title': {
      id: '/work/$title'
      path: '/work/$title'
      fullPath: '/work/$title'
      preLoaderRoute: typeof WorkTitleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$title/': {
      id: '/work/$title/'
      path: '/'
      fullPath: '/work/$title/'
      preLoaderRoute: typeof WorkTitleIndexRouteImport
      parentRoute: typeof WorkTitleRouteRoute
    }
  }
}

interface WorkTitleRouteRouteChildren {
  WorkTitleIndexRoute: typeof WorkTitleIndexRoute
}

const WorkTitleRouteRouteChildren: WorkTitleRouteRouteChildren = {
  WorkTitleIndexRoute: WorkTitleIndexRoute,
}

const WorkTitleRouteRouteWithChildren = WorkTitleRouteRoute._addFileChildren(
  WorkTitleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DevelopmentRoute: DevelopmentRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  WorkTitleRouteRoute: WorkTitleRouteRouteWithChildren,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
